// Generated by CoffeeScript 2.5.1
(function() {
  var Bulk, nanoid;

  ({nanoid} = require('nanoid'));

  Bulk = class Bulk {
    constructor() {
      this.id = nanoid();
      this.count = 0;
      return;
    }

  };

  module.exports = Bulk;

}).call(this);
