// Generated by CoffeeScript 2.5.1
(function() {
  var Bulk;

  Bulk = class Bulk {
    constructor() {
      this.id = Date.now().toString(36);
      this.count = 0;
      return;
    }

  };

  module.exports = Bulk;

}).call(this);
