// Generated by CoffeeScript 2.5.1
(function() {
  var Bulk, Cargo, FOLDER_PREFIX, debuglog, fs, os, path;

  fs = require("fs");

  os = require("os");

  path = require("path");

  debuglog = require("debug")("chcargo:cargo");

  Bulk = require("./bulk");

  FOLDER_PREFIX = "clichouse-cargo-";

  Cargo = class Cargo {
    toString() {
      return `'[Cargo ${this.id}@${this.workingPath}]`;
    }

    constructor(clichouseClient, statement, bulkTTL) {
      this.id = Date.now().toString(36);
      this.count = 0;
      this.workingPath = fs.mkdtempSync(path.join(os.tmpdir(), FOLDER_PREFIX));
      this.curBulk = null;
      this.bulks = [];
      this.moveToNextBulk();
      return;
    }

    moveToNextBulk() {
      if (this.curBulk) {
        this.bulks.push(this.curBulk);
        this.curBulk.upload();
      }
      this.curBulk = new Bulk(this.workingPath);
    }

    exam(forceUpload) {}

    push(data) {
      this.curBulk.push(data);
      return ++this.count;
    }

  };

  module.exports = Cargo;

}).call(this);
