// Generated by CoffeeScript 2.5.1
(function() {
  var cargoOptionToHttpOption, pkg, toSQLDateString;

  pkg = require("../package.json");

  toSQLDateString = function(date) {
    //debuglog "[toSQLDateString] date:", date
    return date.getUTCFullYear() + '-' + ('00' + (date.getUTCMonth() + 1)).slice(-2) + '-' + ('00' + date.getUTCDate()).slice(-2) + ' ' + ('00' + date.getUTCHours()).slice(-2) + ':' + ('00' + date.getUTCMinutes()).slice(-2) + ':' + ('00' + date.getUTCSeconds()).slice(-2);
  };

  cargoOptionToHttpOption = function(cargoOption, mixin) {
    var options;
    options = {
      host: cargoOption.host,
      port: cargoOption.port,
      headers: {
        'X-ClickHouse-User': cargoOption.user,
        'X-ClickHouse-Key': cargoOption.password || '',
        'User-Agent': `${pkg.name}/${pkg.version}`
      }
    };
    return Object.assign(mixin || {}, options);
  };

  module.exports = {
    toSQLDateString: toSQLDateString,
    cargoOptionToHttpOption: cargoOptionToHttpOption
  };

}).call(this);
